//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class login_mst
{
    public login_mst()
    {
        this.sequrity_mst = new HashSet<sequrity_mst>();
    }

    public int login_id { get; set; }
    public Nullable<int> reg_id { get; set; }
    public string user_nm { get; set; }
    public string password1 { get; set; }
    public Nullable<bool> isactive { get; set; }

    public virtual registration_mst registration_mst { get; set; }
    public virtual ICollection<sequrity_mst> sequrity_mst { get; set; }
}

public partial class registration_mst
{
    public registration_mst()
    {
        this.login_mst = new HashSet<login_mst>();
    }

    public int reg_id { get; set; }
    public string first_name { get; set; }
    public string last_name { get; set; }
    public Nullable<System.DateTime> birth_date { get; set; }
    public Nullable<int> ac_no { get; set; }
    public string address1 { get; set; }
    public string branch_name { get; set; }

    public virtual ICollection<login_mst> login_mst { get; set; }
}

public partial class sequrity_mst
{
    public int sec_id { get; set; }
    public Nullable<int> login_id { get; set; }
    public string q1 { get; set; }
    public string ans1 { get; set; }
    public string q2 { get; set; }
    public string ans2 { get; set; }
    public string q3 { get; set; }
    public string ans3 { get; set; }

    public virtual login_mst login_mst { get; set; }
}
