//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_mst
    {
        public login_mst()
        {
            this.sequrity_mst = new HashSet<sequrity_mst>();
        }
    
        public int login_id { get; set; }
        public Nullable<int> reg_id { get; set; }
        public string user_nm { get; set; }
        public string password1 { get; set; }
        public Nullable<bool> isactive { get; set; }
    
        public virtual registration_mst registration_mst { get; set; }
        public virtual ICollection<sequrity_mst> sequrity_mst { get; set; }
    }
}
